<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<t:layout title="승인 활동 기록" active="activity-archive" role="${role}" scriptPath="activity/archive">
    <jsp:body>
    <t:pageHead title="승인 활동 기록" description="최종 승인된 동아리 활동 기록을 확인할 수 있어요."/>
    <section class="rounded-lg border bg-card p-4"><div class="grid gap-3 md:grid-cols-[minmax(0,1fr)_12rem_12rem]"><div><label class="mb-1.5 block text-xs font-extrabold text-muted-foreground" for="archiveKeyword">검색</label><input id="archiveKeyword" type="search" maxlength="150" placeholder="제목 또는 작성자로 검색" class="h-11 w-full rounded-md border border-input bg-background px-3 text-base md:text-sm"></div><div><label class="mb-1.5 block text-xs font-extrabold text-muted-foreground" for="archiveTeam">팀</label><select id="archiveTeam" class="h-11 w-full rounded-md border border-input bg-background px-3 text-base md:text-sm"></select></div><div><label class="mb-1.5 block text-xs font-extrabold text-muted-foreground" for="archiveType">형식</label><select id="archiveType" class="h-11 w-full rounded-md border border-input bg-background px-3 text-base md:text-sm"><option value="">전체 형식</option><option value="SIMPLE">간단 기록</option><option value="HWPX">한글 내역서</option></select></div></div></section>
    <section class="mt-5"><div class="mb-3 flex items-baseline justify-between"><h2 class="text-lg font-black">전체 기록</h2><p class="text-xs text-muted-foreground" data-archive-summary></p></div><div class="grid grid-cols-1 gap-4 lg:grid-cols-2" data-archive-list></div><div class="rounded-lg border bg-card px-5 py-11 text-center" data-archive-state role="status" aria-live="polite"><b class="block text-sm font-extrabold" data-archive-state-title>승인 기록을 불러오는 중입니다</b><p class="mt-1 text-xs text-muted-foreground" data-archive-state-message>잠시만 기다려 주세요.</p><button type="button" class="mt-4 hidden min-h-11 rounded-md border px-4 text-xs font-bold" data-page-action="activity-archive-retry" data-archive-retry>다시 시도</button></div><t:pagination id="activityArchivePagination" label="승인 활동 기록 페이지"/></section>
    <template data-archive-card-template><article class="overflow-hidden rounded-lg border bg-card"><div class="flex flex-col sm:flex-row"><div class="relative flex h-40 shrink-0 items-center justify-center overflow-hidden bg-secondary sm:h-auto sm:w-44"><img class="hidden size-full object-cover" data-archive-image alt=""><span class="px-4 text-center text-xs font-bold text-muted-foreground" data-archive-image-fallback>인증 사진 없음</span></div><div class="min-w-0 flex-1 p-5"><div class="flex flex-wrap gap-2" data-archive-badges></div><h3 class="mt-3 text-base font-black" data-archive-title></h3><p class="mt-2 text-xs text-muted-foreground" data-archive-meta></p><p class="mt-3 text-xs text-muted-foreground" data-archive-author></p><a class="mt-4 inline-flex min-h-11 items-center rounded-md border px-3 text-xs font-bold hover:bg-secondary" data-archive-detail>상세 보기</a><a class="mt-2 hidden min-h-11 items-center rounded-md border px-3 text-xs font-bold hover:bg-secondary" data-archive-hwpx>HWPX 다운로드</a></div></div></article></template>
    </jsp:body>
</t:layout>
