<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="t" tagdir="/WEB-INF/tags" %>
<t:layout title="자료실" active="resources" role="${role}" scriptPath="resources/list">
    <t:pageHead title="자료실" description="업무 자료와 파일 리비전을 한곳에서 관리합니다."><c:if test="${role != 'member'}"><t:button pageAction="resource-create">자료 업로드</t:button></c:if></t:pageHead>
    <div class="mb-4 space-y-3">
        <input class="h-11 w-full rounded-md border border-input bg-card px-3 text-sm" type="search" data-resource-search placeholder="제목·설명·수정자로 검색" aria-label="자료 검색">
        <div class="flex flex-wrap items-center gap-2" aria-label="자료 필터">
            <t:filterChip group="resource-category" value="ALL" label="전체 분류" active="true"/><t:filterChip group="resource-category" value="SCRIPT" label="대본"/><t:filterChip group="resource-category" value="MINUTES" label="회의록"/><t:filterChip group="resource-category" value="PROMOTION" label="홍보물"/><t:filterChip group="resource-category" value="VIDEO" label="영상"/><t:filterChip group="resource-category" value="OTHER" label="기타"/>
            <span class="mx-1 hidden h-6 border-l md:block" aria-hidden="true"></span>
            <t:filterChip group="resource-scope" value="ANY" label="전체 범위" active="true"/><t:filterChip group="resource-scope" value="ALL" label="전체 공용"/><t:filterChip group="resource-scope" value="TEAM" label="팀 자료"/>
        </div>
    </div>
    <t:card flush="true"><t:dataTable caption="자료 목록"><thead><tr><th>자료</th><th>분류</th><th>버전</th><th>수정일</th><th></th></tr></thead><tbody data-resource-list><tr data-resource-state><td colspan="5" class="px-5 py-11 text-center"><b class="block text-sm" data-resource-state-title>자료를 불러오는 중입니다</b><p class="mt-1 text-xs text-muted-foreground" data-resource-state-message>잠시만 기다려 주세요.</p><div class="mt-4 flex justify-center gap-2"><button type="button" class="hidden min-h-11 rounded-md border px-4 text-sm font-bold" data-resource-reset>필터 초기화</button><button type="button" class="hidden min-h-11 rounded-md border px-4 text-sm font-bold" data-resource-retry>다시 시도</button></div></td></tr></tbody></t:dataTable></t:card>
    <t:pagination id="resourcePagination" label="자료 목록 페이지"/>
    <template data-resource-row-template><tr data-resource-row><td><b data-resource-title></b><span class="mt-1 block text-xs text-muted-foreground" data-resource-meta></span></td><td data-resource-category></td><td data-resource-version></td><td data-resource-date></td><td><div class="flex flex-wrap justify-end gap-1" data-resource-actions></div></td></tr></template>
    <t:modal id="resourceFormModal" title="자료 업로드"><jsp:attribute name="footer"><t:button variant="outline" action="close-modal">취소</t:button><t:button pageAction="resource-save">자료 저장</t:button></jsp:attribute><jsp:body><div class="space-y-3"><div><label class="mb-1 block text-xs font-extrabold" for="resourceTitle">제목</label><input id="resourceTitle" class="h-11 w-full rounded-md border px-3" maxlength="200"></div><div class="grid gap-3 md:grid-cols-2"><select id="resourceCategory" class="h-11 rounded-md border px-3"><option value="SCRIPT">대본</option><option value="MINUTES">회의록</option><option value="PROMOTION">홍보물</option><option value="VIDEO">영상</option><option value="OTHER">기타</option></select><select id="resourceTarget" class="h-11 rounded-md border px-3"><c:if test="${role == 'admin'}"><option value="ALL">전체</option></c:if><option value="TEAM">내 팀</option></select></div><div class="hidden" data-resource-team-wrap><label class="mb-1 block text-xs font-extrabold" for="resourceTeam">대상 팀</label><select id="resourceTeam" class="h-11 w-full rounded-md border px-3"></select></div><textarea id="resourceDescription" class="min-h-24 w-full rounded-md border p-3" placeholder="자료의 용도를 입력하세요"></textarea><input id="resourceFile" type="file" class="block w-full text-sm"><label class="flex gap-2 text-sm"><input id="resourcePinned" type="checkbox"> 상단 고정</label><p class="hidden text-xs text-destructive" data-resource-error></p></div></jsp:body></t:modal>
    <t:modal id="resourceHistoryModal" title="자료 파일 이력"><jsp:attribute name="footer"><t:button variant="outline" action="close-modal">닫기</t:button></jsp:attribute><jsp:body><div class="space-y-3 text-sm" data-resource-history-list></div></jsp:body></t:modal>
</t:layout>
